web:
  build: .
  links:
    - postgres
    - rabbitmq
  ports: "5000:5000"
  env_file:
    - '.env.docker'
socket1:
  build: .
  links:
    - postgres
    - rabbitmq
  ports: "6480:5000"
  env_file:
    - '.env.docker'
socket2:
  build: .
  links:
    - postgres
    - rabbitmq
  ports: "6481:5000"
  env_file:
    - '.env.docker'
postgres:
  image: postgres:9.4
  expose:
    - "5432"
  env_file:
    - '.env.docker'
rabbitmq:
  image: rabbitmq:3.5
  hostname: rabbit1
  expose:
    - "5672"
  env_file:
    - '.env.docker'
